name: "[Manual] Util: Create Release"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Name of the tag
        required: true
      manualDate:
        description: "Type a date manually if you want to use it instead of today (format: YYYY-MM-DD)"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: prod
      - name: Create Release date
        id: create_release_date
        run: |
          manualDate=${{ inputs.manualDate }}
          if [ -z "$manualDate" ]
          then
                echo "DATE=`date '+[%Y-%m-%d]'`" >> $GITHUB_OUTPUT
          else
                echo "DATE=[$manualDate]" >> $GITHUB_OUTPUT
          fi
      - name: Create Release name
        id: create_release_name
        run: |
          tag_name=${{ inputs.tag }}
          date=${{ steps.create_release_date.outputs.DATE }}
          capitalized_tag_name="${tag_name^}"
          release_name="Release ${capitalized_tag_name//-/ } $date"
          echo "RELEASE_NAME=$release_name" >> $GITHUB_OUTPUT

      - name: "Create release"
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_NAME,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: "${{ inputs.tag }}",
              });

              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }