name: Create deployment pull request
on:
  workflow_dispatch:
      # Inputs the workflow accepts.
      inputs:
        name:
          # Friendly description to be shown in the UI instead of 'name'
          description: 'Sprint name'
          # Input has to be provided for the workflow to run
          required: true
        asana_token:
          description: 'Asana token'
          required: true
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev

      - name: Create PR Name
        id: create_pr_name
        run: |
          echo "PR_NAME=${${{ inputs.name }}^}" >> $GITHUB_OUTPUT

      - name: Delete existing branch
        run: |
          git push origin --delete dev-to-staging-${{ inputs.name }}
        continue-on-error: true

      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'dev-to-staging-${{ inputs.name }}'
  
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: 'dev'
          target_branch: 'dev-to-staging-${{ inputs.name }}'

      - name: Create pull request
        id: pr
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: dev-to-staging-${{ inputs.name }}
          base: staging
          title: "Dev to staging ${{ steps.create_pr_name.PR_NAME }}"
          labels: "deploy"

      - name: Extract ticket numbers
        uses: ./.github/actions/extract-ticket-numbers
        with:
          github_token: ${{ github.token }}
          pull_request: "${{ steps.pr.outputs.number }}"
          asana_token: ${{ inputs.asana_token }}