name: Echo when push on branch
on:
  pull_request:
    types:
      - closed
    branches:
      - 'prod'
jobs:
  echo:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "Pull request ${{ github.event.pull_request.number }} merged on branch ${{ github.ref }}"
