name: Echo when push on a branch
on:
  push:
    - '**'
jobs:
  echo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Echoes to know this worked
        run: echo "It worked"